language: java
sudo: false
install: true
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
dist: trusty
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
